
const ActivityConstants = {

  RECEIVE_ACTIVITIES   : "RECEIVE_ACTIVITIES",
  RECEIVE_ACTIVITY     : "RECEIVE_ACTIVITY",
  RECEIVE_NEW_ACTIVITY : "RECEIVE_NEW_ACTIVITY",
  REMOVE_ACTIVITY      : "REMOVE_ACTIVITY"

};

module.exports = ActivityConstants;
